### ISSUE TITLE
Cuda memory is full when import

### ISSUE THREAD

**Issue by ZhangZef** [PythonOT/POT#573] opened 2023-11-10 13:07 UTC
## Describe the bug

I'm just using the `import ot` in my `test.py` and it causes all the cuda memory of my first GPU to be full

#### Screenshots

<img width="1210" alt="image" src="https://github.com/PythonOT/POT/assets/39962066/6c6ef680-1638-4dc0-9817-20a57d240074">

### Environment (please complete the following information):
- OS (e.g. MacOS, Windows, Linux): Linux
- Python version: 3.10.13
- POT version: 0.9.1
- How was POT installed (source, `pip`, `conda`): pip
- Only for GPU related bugs:
    - CUDA version: 12.0

Output of the following code snippet:
```python
import ot
import pdb

pdb.set_trace()
print()
```

**Comment by rflamary** [comment] 2023-11-10 13:13
Yes this is a duplicate of #516 so I'm closing It. It  shoudl be fixed in the master branch if you want to test it.

**Closed by rflamary** 2023-11-10 13:13 UTC
Labels: bug, help wanted
